export const nameToLabelMap = {
  code: "Код",
  name: "Назва",
  // serial: "Серійний номер",
  barcode: "Штрихкод",
  // globalCode: "Глобальний код",
  tax: "Код податку",
  price: "Ціна",
  isWeight: "Ваговий товар",
  // mrcPrice: "MRC Ціна",
  amount: "Кількість",
  group: "Група",
  uktzed: "УКТЗЕД",
  unit: "Од. вим.",
  freePrice: "Довільна ціна",
};

export const exampleData = [
  {
    [nameToLabelMap.code]: 1,
    [nameToLabelMap.name]: "Кава Arabica 250г",
    // [nameToLabelMap.serial]: "SN001",
    [nameToLabelMap.barcode]: "4820001111111",
    // [nameToLabelMap.globalCode]: "GLB001",
    [nameToLabelMap.price]: 210,
    [nameToLabelMap.group]: "Кава",
    [nameToLabelMap.uktzed]: "0901210000",
    [nameToLabelMap.unit]: "шт",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 1,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 2,
    [nameToLabelMap.name]: "Цукор білий 1 кг",
    // [nameToLabelMap.serial]: "SN002",
    [nameToLabelMap.barcode]: "4820002222222",
    // [nameToLabelMap.globalCode]: "GLB002",
    [nameToLabelMap.price]: 32,
    [nameToLabelMap.group]: "Продукти",
    [nameToLabelMap.uktzed]: "1701991000",
    [nameToLabelMap.unit]: "кг",
    [nameToLabelMap.isWeight]: true,
    [nameToLabelMap.tax]: 1,
    [nameToLabelMap.freePrice]: false,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 3,
    [nameToLabelMap.name]: "Вода мінеральна 0.5л",
    // [nameToLabelMap.serial]: "SN003",
    [nameToLabelMap.barcode]: "4820003333333",
    // [nameToLabelMap.globalCode]: "GLB003",
    [nameToLabelMap.price]: 18,
    [nameToLabelMap.group]: "Напої",
    [nameToLabelMap.uktzed]: "2201101900",
    [nameToLabelMap.unit]: "шт",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 1,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 4,
    [nameToLabelMap.name]: "Печиво «Домашнє» 500г",
    // [nameToLabelMap.serial]: "SN004",
    [nameToLabelMap.barcode]: "4820004444444",
    // [nameToLabelMap.globalCode]: "GLB004",
    [nameToLabelMap.price]: 85,
    [nameToLabelMap.group]: "Випічка",
    [nameToLabelMap.uktzed]: "1905310000",
    [nameToLabelMap.unit]: "уп.",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 1,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 5,
    [nameToLabelMap.name]: "Молоко 2.5% 1л",
    // [nameToLabelMap.serial]: "SN005",
    [nameToLabelMap.barcode]: "4820005555555",
    // [nameToLabelMap.globalCode]: "GLB005",
    [nameToLabelMap.price]: 36,
    [nameToLabelMap.group]: "Молочні продукти",
    [nameToLabelMap.uktzed]: "0401209100",
    [nameToLabelMap.unit]: "л",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 1,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 6,
    [nameToLabelMap.name]: "Сир твердий «Гауда» 1 кг",
    // [nameToLabelMap.serial]: "SN006",
    [nameToLabelMap.barcode]: "4820006666666",
    // [nameToLabelMap.globalCode]: "GLB006",
    [nameToLabelMap.price]: 320,
    [nameToLabelMap.group]: "Молочні продукти",
    [nameToLabelMap.uktzed]: "0406903000",
    [nameToLabelMap.unit]: "кг",
    [nameToLabelMap.isWeight]: true,
    [nameToLabelMap.tax]: 2,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 7,
    [nameToLabelMap.name]: "Пакет поліетиленовий",
    // [nameToLabelMap.serial]: "SN007",
    [nameToLabelMap.barcode]: "4820007777777",
    // [nameToLabelMap.globalCode]: "GLB007",
    [nameToLabelMap.price]: 2,
    [nameToLabelMap.group]: "Упаковка",
    [nameToLabelMap.uktzed]: "3923210000",
    [nameToLabelMap.unit]: "шт",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 3,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 8,
    [nameToLabelMap.name]: "Хліб житній 700г",
    // [nameToLabelMap.serial]: "SN008",
    [nameToLabelMap.barcode]: "4820008888888",
    // [nameToLabelMap.globalCode]: "GLB008",
    [nameToLabelMap.price]: 42,
    [nameToLabelMap.group]: "Випічка",
    [nameToLabelMap.uktzed]: "1905907000",
    [nameToLabelMap.unit]: "шт",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 4,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 9,
    [nameToLabelMap.name]: "Сигарети Marlboro Gold",
    // [nameToLabelMap.serial]: "SN009",
    [nameToLabelMap.barcode]: "4820009999999",
    // [nameToLabelMap.globalCode]: "GLB009",
    [nameToLabelMap.price]: 95,
    [nameToLabelMap.group]: "Тютюнові вироби",
    [nameToLabelMap.uktzed]: "2402209000",
    [nameToLabelMap.unit]: "пачка",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 3,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
  {
    [nameToLabelMap.code]: 10,
    [nameToLabelMap.name]: "Батарейки AA (пара)",
    // [nameToLabelMap.serial]: "SN010",
    [nameToLabelMap.barcode]: "4820010101010",
    // [nameToLabelMap.globalCode]: "GLB010",
    [nameToLabelMap.price]: 28,
    [nameToLabelMap.group]: "Електроніка",
    [nameToLabelMap.uktzed]: "8506101100",
    [nameToLabelMap.unit]: "уп.",
    [nameToLabelMap.isWeight]: false,
    [nameToLabelMap.tax]: 2,
    [nameToLabelMap.freePrice]: true,
    [nameToLabelMap.amount]: 1,
  },
];

export const exampleTaxes = [
  { Код: 1, Назва: "ПДВ 20%" },
  { Код: 2, Назва: "ПДВ 7%" },
  { Код: 3, Назва: "Без ПДВ" },
  { Код: 4, Назва: "Акциз + ПДВ 20%" },
];

export const exampleGroups = [
  { Код: 1, Назва: "Основна", Підакцизна: false, Розлив: false },
  { Код: 2, Назва: "Кава", Підакцизна: false, Розлив: false },
  { Код: 3, Назва: "Напої", Підакцизна: false, Розлив: true },
  { Код: 4, Назва: "Продукти", Підакцизна: false, Розлив: false },
  { Код: 5, Назва: "Молочні продукти", Підакцизна: false, Розлив: false },
  { Код: 6, Назва: "Випічка", Підакцизна: false, Розлив: false },
  { Код: 7, Назва: "Упаковка", Підакцизна: false, Розлив: false },
  { Код: 8, Назва: "Тютюнові вироби", Підакцизна: true, Розлив: false },
  { Код: 9, Назва: "Електроніка", Підакцизна: false, Розлив: false },
];
